# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Job pour Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Job pour vos services PFE (Docker Compose)
  - job_name: 'pfe-services'
    static_configs:
      - targets: 
          - 'spacy_service:5003'           # ✅ Services Flask
          - 'sklearn-IF_service:5001'      
          - 'sklearn-OCSVM_service:5002'   
          - 'chatbot_web:8000'             
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # ✅ NOUVEAU : Job pour Node Exporter (métriques système)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # ✅ AJOUTER Node Exporter
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Job pour Grafana 
  - job_name: 'grafana'
    static_configs:
      - targets: ['my_grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
