apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: pfe-app
data:
  prometheus.yml: |
    # Copie du contenu du fichier prometheus.yml
    # (à remplacer par le vrai contenu si besoin)
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090'] 