apiVersion: apps/v1
kind: Deployment
metadata:
  name: sklearn-if-service
  namespace: pfe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sklearn-if-service
  template:
    metadata:
      labels:
        app: sklearn-if-service
    spec:
      containers:
        - name: sklearn-if-service
          image: eyaboulaaba/pfe:sklearn-if-service  # Image depuis Docker Hub
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"
            - name: FLASK_RUN_PORT
              value: "5001"
            - name: SPACY_API_URL
              value: "http://spacy-service:5003"
---
apiVersion: v1
kind: Service
metadata:
  name: sklearn-if-service
  namespace: pfe-app
spec:
  selector:
    app: sklearn-if-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP