apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-service
  namespace: pfe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-service
  template:
    metadata:
      labels:
        app: ollama-service
    spec:
      containers:
        - name: ollama-service
          image: ollama/ollama:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 11434
          env:
            - name: OLLAMA_KEEP_ALIVE
              value: "24h"
            - name: OLLAMA_HOST
              value: "0.0.0.0:11434"
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: pfe-app
spec:
  selector:
    app: ollama-service
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP