apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-web
  namespace: pfe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-web
  template:
    metadata:
      labels:
        app: chatbot-web
    spec:
      containers:
        - name: chatbot-web
          image: eyaboulaaba/pfe:chatbot-web-service-lates # Image depuis Docker Hub
          

          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: OLLAMA_URL
              value: "http://ollama-service:11434"
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"
            - name: FLASK_RUN_PORT
              value: "8000"
            - name: SPACY_API_URL
              value: "http://spacy-service:5003"
            - name: SKLEARN_API_URL_5001
              value: "http://sklearn-if-service:5001"
            - name: SKLEARN_API_URL_5002
              value: "http://sklearn-ocsvm-service:5002"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-web
  namespace: pfe-app
spec:
  selector:
    app: chatbot-web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort