apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacy-service
  namespace: pfe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacy-service
  template:
    metadata:
      labels:
        app: spacy-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5003"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: spacy-service
          image: eyaboulaaba/pfe:spacy-service-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
              name: http
          env:
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"
            - name: FLASK_RUN_PORT
              value: "5003"
---
apiVersion: v1
kind: Service
metadata:
  name: spacy-service
  namespace: pfe-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5003"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: spacy-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
      name: http
  type: ClusterIP


