apiVersion: apps/v1
kind: Deployment
metadata:
  name: sklearn-if-service
  namespace: pfe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sklearn-if-service
  template:
    metadata:
      labels:
        app: sklearn-if-service
    spec:
      containers:
      - name: sklearn-if-service
        image: eyaboulaaba/pfe:sklearn-if-service-latest
        ports:
        - containerPort: 5001  # Vérifiez le port dans votre Dockerfile
---
apiVersion: v1
kind: Service
metadata:
  name: sklearn-if-service
  namespace: pfe-app
spec:
  selector:
    app: sklearn-if-service
  ports:
  - port: 5001
    targetPort: 5001
  type: ClusterIP