# ⚠️ NOUVEAU FICHIER À CRÉER

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: pfe-app  # ✅ CHANGÉ de monitoring vers pfe-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # Prometheus lui-même
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
        scrape_interval: 5s

      # ✅ VOS SERVICES PFE (même namespace)
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+)
            replacement: ${__meta_kubernetes_pod_ip}:${1}
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: kubernetes_pod_name
          # ✅ UNIQUEMENT namespace pfe-app
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: pfe-app

      # ✅ NODE EXPORTER dans même namespace
      - job_name: 'kubernetes-nodes'
        static_configs:
          - targets: ['node-exporter.pfe-app.svc.cluster.local:9100']  # ✅ CHANGÉ
        scrape_interval: 15s
        metrics_path: '/metrics'

      # ✅ GRAFANA dans même namespace  
      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana.pfe-app.svc.cluster.local:3000']  # ✅ AJOUTÉ
        scrape_interval: 30s
        metrics_path: '/metrics'