apiVersion: apps/v1
kind: Deployment
metadata:
  name: sklearn-ocsvm-service
  namespace: pfe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sklearn-ocsvm-service
  template:
    metadata:
      labels:
        app: sklearn-ocsvm-service
    spec:
      containers:
      - name: sklearn-ocsvm-service
        image: eyaboulaaba/pfe:sklearn-ocsvm-service-latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: sklearn-ocsvm-service
  namespace: pfe-app
spec:
  selector:
    app: sklearn-ocsvm-service
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP