apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacy-service
  namespace: pfe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacy-service
  template:
    metadata:
      labels:
        app: spacy-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5003"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: spacy-service
        image: eyaboulaaba/pfe:spacy-service-latest
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: spacy-service
  namespace: pfe-app
spec:
  selector:
    app: spacy-service
  ports:
  - port: 5003
    targetPort: 5003
  type: ClusterIP