version: "3.8"
services:
  jenkins:
    build: .
    container_name: jenkins
    user: root # Ajoutez cette ligne pour résoudre les permissions
    ports:
      - "8080:8080" # Interface web Jenkins
      - "50000:50000" # Port pour les agents Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
    environment:
      - JENKINS_OPTS=--httpPort=8080

volumes:
  jenkins_home:
