FROM jenkins/jenkins:lts

# Optionnel : installer des plugins ou outils supplémentaires ici
# RUN jenkins-plugin-cli --plugins blueocean:1.25.0

# Jenkins écoute sur le port 8080 (web) et 50000 (agent)
EXPOSE 8080 50000 
# hel