global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'your_service_name'
    static_configs:
      - targets: ['your_service:your_service_port']  # Replace with your actual service name and port

# Add additional scrape configurations as needed for other services